### ISSUE TITLE
Что означают сокращения ?

### ISSUE THREAD

**Issue by hpkit** [sirily/ru_base#2]
Подскажите, что значат CD, 16 DEN, 2000 sen + lm_test ?
В model_parameters куча каталогов,какой использовать ? Где брать словари и модель языковую ?

**Comment by sirily** [comment]
Прошу прощения за такой долгий ответ, я пару лет сюда не заходил.
В общем-то это модель, которая была построена в рамках лабораторной работы, которую я с одним товарищем разрабатывал для университета, поэтому я уже в точности не помню нюансов её работы. Словари и сама модель, насколько я помню, лежат в папке etc. Те, которые с расширением .lm - языковые модели, .dic словари и тд.
CD - это context-dependent, что означает тренировку модели по контекстно-зависимым трифонам. Это параметр в конфигурационном файле etc/sphinx_train.cfg. CI, соответственно, контекстно-независимые.
16 Den - это количество Гауссиан. Так как в модели для каждой фонемы используются смеси этих Гауссиан (параметр $CFG_FINAL_NUM_DENSITIES в конфиге).
2000 sen - это количество сенонов (последовательностей фонем), параметр $CFG_N_TIED_STATES в конфиге.

Я напишу товарищу, с которым мы работали, и если он не против, прикреплю к проекту методичку, которую он сделал. С ней будет понятнее

**Comment by hpkit** [comment]
А можете еще выложить материалы  материалы (lab_sphinx/theory) ?

**Comment by sirily** [comment]
Выложил все материалы, которые у меня есть. Переименовал репозиторий так как папка ru_base стала его частью. В ней вы всё ещё сможете найти те файлы, которые были в проекте ранее
